---
driver:
  name: docker

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[packages::default]
